name: Docker Image

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: docker-postfix-noreply
            image_tag: '1.0'
            verify_path: /entrypoint.sh

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and load docker images
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: ${{ matrix.image_name }}:${{ matrix.image_tag }}

      - name: Verify docker images built success
        run: docker run --rm --entrypoint "/bin/bash" ${{ matrix.image_name }}:${{ matrix.image_tag }} -c "if [ -e ${{ matrix.verify_path }} ]; then (exit 0); else (exit 1); fi"

      - name: Build and push docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ matrix.image_tag }}, ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image_name }}:latest

